name: landingpage
description: Cross platform sample landing page implemented in Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.3.0-dev.68.0 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  #dependencies to enable the Dart web build system
  build_runner: ^1.4.0 # ^1.3.5 (building site)
  build_web_compilers: ^2.0.0
  flutter_web_test: any

flutter:
  uses-material-design: true

  ## These overrides tell the package tools to get them from GitHub
dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test
